import type { Config } from 'tailwindcss'

export default {
  content: [
    './pages/**/*.{vue,js,ts}',
    './layouts/**/*.{vue,js,ts}',
    './components/**/*.{vue,js,ts}',
    './middleware/**/*.{js,ts}',
    './app.vue',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint':                  '#4c5d8e',
        'primary-fixed-dim':             '#b4c5fc',
        'primary':                       '#021745',
        'on-tertiary':                   '#ffffff',
        'surface-container-highest':     '#e2e3e1',
        'on-secondary-fixed-variant':    '#783200',
        'on-secondary-container':        '#5c2400',
        'inverse-primary':               '#b4c5fc',
        'outline-variant':               '#c5c6d0',
        'tertiary-fixed-dim':            '#d2bbff',
        'surface-bright':                '#f9f9f7',
        'on-secondary':                  '#ffffff',
        'error-container':               '#ffdad6',
        'on-tertiary-container':         '#a97fff',
        'on-primary-fixed-variant':      '#344574',
        'on-error-container':            '#93000a',
        'surface-container':             '#eeeeec',
        'tertiary-container':            '#3d008b',
        'on-primary-container':          '#8595ca',
        'surface-container-high':        '#e8e8e6',
        'tertiary':                      '#240057',
        'on-tertiary-fixed':             '#25005a',
        'inverse-surface':               '#2f3130',
        'tertiary-fixed':                '#eaddff',
        'surface-container-low':         '#f4f4f2',
        'on-primary':                    '#ffffff',
        'on-surface':                    '#1a1c1b',
        'on-tertiary-fixed-variant':     '#5a00c6',
        'surface-variant':               '#e2e3e1',
        'on-background':                 '#1a1c1b',
        'inverse-on-surface':            '#f1f1ef',
        'outline':                       '#757680',
        'secondary-fixed':               '#ffdbca',
        'on-secondary-fixed':            '#341100',
        'secondary-fixed-dim':           '#ffb690',
        'surface-dim':                   '#dadad8',
        'error':                         '#ba1a1a',
        'background':                    '#f9f9f7',
        'surface-container-lowest':      '#ffffff',
        'secondary-container':           '#fd761a',
        'primary-fixed':                 '#dbe1ff',
        'on-error':                      '#ffffff',
        'on-surface-variant':            '#45464f',
        'surface':                       '#f9f9f7',
        'secondary':                     '#9d4300',
        'primary-container':             '#1b2d5b',
        'on-primary-fixed':              '#031846',
        'brand-orange':                  '#F97316',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '12px',
        xl:      '12px',
        full:    '9999px',
      },
      spacing: {
        // ── Customer ──────────────────────────────────────────────────────────
        base:            '4px',
        lg:              '24px',
        xs:              '4px',
        'margin-mobile': '16px',
        xl:              '32px',
        gutter:          '16px',
        sm:              '8px',
        'margin-tablet': '24px',
        md:              '16px',
        // ── Admin ─────────────────────────────────────────────────────────────
        'stack-lg':          '24px',
        'stack-md':          '16px',
        'stack-sm':          '8px',
        'admin-gutter':      '24px',
        'sidebar-width':     '260px',
        'container-padding': '32px',
      },
      fontFamily: {
        // ── Customer (Hanken Grotesk) ─────────────────────────────────────────
        'headline-md':        ['Hanken Grotesk', 'sans-serif'],
        'body-sm':            ['Hanken Grotesk', 'sans-serif'],
        'label-bold':         ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'status-badge':       ['Hanken Grotesk', 'sans-serif'],
        'headline-lg':        ['Hanken Grotesk', 'sans-serif'],
        'body-lg':            ['Hanken Grotesk', 'sans-serif'],
        // ── Admin (Work Sans) ─────────────────────────────────────────────────
        'work-sans':          ['Work Sans', 'sans-serif'],
        'body-md':            ['Work Sans', 'sans-serif'],
        'display-lg':         ['Work Sans', 'sans-serif'],
        'title-sm':           ['Work Sans', 'sans-serif'],
        'label-caps':         ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        // ── Customer ──────────────────────────────────────────────────────────
        'headline-md':        ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold':         ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'status-badge':       ['11px', { lineHeight: '12px', fontWeight: '800' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        // ── Admin ─────────────────────────────────────────────────────────────
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg':         ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'title-sm':           ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'label-caps':         ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
