// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23/06/2026, 14:35:43
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Barake/Desktop/repos/kaban-printing-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/stores/**/*.{js,ts,mjs}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/composables/**/*.{js,ts,mjs}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/utils/**/*.{js,ts,mjs}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Barake/Desktop/repos/kaban-printing-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;